name: Pipeline
on:
  pull_request:
    paths-ignore:
      - 'images/**'
jobs:
  verify:
    name: Build and Verify
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Docker QEMU (To target RPi ARM)
        uses: docker/setup-qemu-action@v1
        with:
          image: docker://ghcr.io/samsonmking/epaperjs-docker:v2.0.0
          platforms: arm/v7
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: docker://ghcr.io/samsonmking/epaperjs-docker:v2.0.0
        with:
          entrypoint: pnpm
          args: install
      - name: Build Bindings
        uses: docker://ghcr.io/samsonmking/epaperjs-docker:v2.0.0
        with:
          entrypoint: pnpm
          args: clean:build
      - name: Build Typescript
        uses: docker://ghcr.io/samsonmking/epaperjs-docker:v2.0.0
        with:
          entrypoint: pnpm
          args: clean:compile
      - name: Check Formatting
        uses: docker://ghcr.io/samsonmking/epaperjs-docker:v2.0.0
        with:
          entrypoint: pnpm
          args: format:check
